"""
Extended version của LanguageModelOllama tích hợp sẵn tokenizer 
để tương thích trực tiếp với MapReduceLLM
"""

import sys
import os
# from llm_mapreduce.mapreduce import MapReduceLLM
# Thêm path
sys.path.insert(0, '/home/bojjoo/Code/EduAssist')

from api.services.local_llm import LanguageModelOllama
from transformers import AutoTokenizer
from typing import Dict


class LanguageModelOllamaMapReduce(LanguageModelOllama):
    """
    Mở rộng LanguageModelOllama để tương thích với MapReduceLLM
    Thêm tokenizer và format lại output
    
    QUAN TRỌNG: Class này override các phương thức để tương thích với
    MapReduceLLM framework, vốn được thiết kế cho PyTorch models.
    """
    
    def __init__(self, model: str, tokenizer_name: str = None, 
                 stream: bool = False, temperature: float = 0.7,
                 host: str = "http://localhost:11434", request_timeout: float = 60.0, 
                 max_retries: int = 2):
        """
        Args:
            model: Tên model Ollama đã pull (vd: "shmily_006/Qw3:4b_4bit")
            tokenizer_name: Tên tokenizer từ HuggingFace. Nếu None, sẽ tự động chọn:
                           - Qwen models → "Qwen/Qwen2.5-7B"
                           - Llama models → "meta-llama/Llama-3.2-3B" 
                           - Khác → "vinai/phobert-base" (tiếng Việt)
            stream: Stream response hay không
            temperature: Nhiệt độ generation
            host: Địa chỉ Ollama server
            request_timeout: Timeout cho request
            max_retries: Số lần retry khi lỗi
        """
        # Gọi constructor của class cha
        super().__init__(model, stream, temperature, host, request_timeout, max_retries)
        
        # Auto-detect tokenizer nếu không được chỉ định
        if tokenizer_name is None:
            tokenizer_name = self._auto_detect_tokenizer(model)
            print(f"🔍 Auto-detected tokenizer: {tokenizer_name}")
        
        # Thêm tokenizer (MapReduce cần để đếm tokens)
        print(f"Đang tải tokenizer: {tokenizer_name}...")
        self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
        
        # Đặt pad_token nếu chưa có (một số tokenizer không có)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        
        # Thêm thuộc tính device để tương thích với MapReduce
        # (MapReduce mong đợi PyTorch model, nhưng ta dùng Ollama API)
        self.device = "cpu"  # Dummy value vì Ollama chạy trên server riêng
    
    def _auto_detect_tokenizer(self, model_name: str) -> str:
        """
        Tự động phát hiện tokenizer phù hợp dựa trên tên model
        
        Args:
            model_name: Tên model Ollama (vd: "shmily_006/Qw3:4b_4bit", "llama3.2:3b")
            
        Returns:
            Tên tokenizer HuggingFace phù hợp
        """
        model_lower = model_name.lower()
        
        # Llama models
        if 'llama' in model_lower:
            if 'llama3' in model_lower:
                return "meta-llama/Llama-3.2-3B"
            return "meta-llama/Llama-3.2-3B"
        
        # Phi models
        if 'phi' in model_lower:
            return "microsoft/Phi-3-mini-4k-instruct"
        
        # Gemma models
        if 'gemma' in model_lower:
            return "google/gemma-2-2b"
        
        # Mistral models
        if 'mistral' in model_lower or 'mixtral' in model_lower:
            return "mistralai/Mistral-7B-v0.1"
        
        # Default: PhoBERT cho tiếng Việt
        print(f"   ⚠️  Không nhận diện được model {model_name}, dùng PhoBERT (tiếng Việt)")
        return "vinai/phobert-base"
    
    def generate(self, query: str) -> Dict:
        """
        Override phương thức generate để trả về format mà MapReduce yêu cầu
        
        Args:
            query: Prompt/câu hỏi
            
        Returns:
            Dict với keys: "text", "answer", "rationale"
        """
        # Gọi hàm generate gốc từ class cha
        response = super().generate(query)
        
        # Format lại theo yêu cầu của MapReduce
        return {
            "text": response,
            "answer": response,
            "rationale": f"Generated by Ollama model: {self.model}"
        }
    
    def process_chunk(self, chunk: str, query: str) -> Dict:
        """
        Xử lý một chunk văn bản với query
        Phương thức này được gọi bởi MapReduceLLM.map_stage()
        
        Args:
            chunk: Đoạn văn bản cần xử lý
            query: Câu hỏi/yêu cầu
            
        Returns:
            Dict với keys: "text", "answer", "rationale"
        """
        # Tạo prompt kết hợp query và chunk
        combined_input = f"{query}\n\nDocument:\n{chunk}"
        
        # Truncate nếu quá dài (dựa trên tokenizer)
        tokens = self.tokenizer.encode(combined_input)
        max_tokens = getattr(self.tokenizer, 'model_max_length', 4096)
        
        if len(tokens) > max_tokens:
            # Cắt bớt chunk để vừa context window
            truncated_tokens = tokens[:max_tokens]
            combined_input = self.tokenizer.decode(truncated_tokens, skip_special_tokens=True)
        
        # Gọi Ollama API
        response = self.generate(combined_input)
        
        return response


# ============= VÍ DỤ SỬ DỤNG =============

class OllamaMapReduceLLM:
    """
    Custom MapReduce implementation cho Ollama models
    Khắc phục vấn đề không tương thích với MapReduceLLM gốc (thiết kế cho PyTorch)
    """
    
    def __init__(self, model: LanguageModelOllamaMapReduce, context_window: int = 4096, 
                 collapse_threshold: int = 2048):
        """
        Args:
            model: Instance của LanguageModelOllamaMapReduce
            context_window: Kích thước context window
            collapse_threshold: Ngưỡng để collapse chunks
        """
        self.model = model
        self.context_window = context_window
        self.collapse_threshold = collapse_threshold
    
    def chunk_text(self, text: str) -> list:
        """Chia văn bản thành các chunks"""
        tokens = self.model.tokenizer.encode(text)
        chunks = []
        
        for i in range(0, len(tokens), self.context_window):
            chunk_tokens = tokens[i:i + self.context_window]
            chunk_text = self.model.tokenizer.decode(chunk_tokens, skip_special_tokens=True)
            chunks.append(chunk_text)
        
        return chunks
    
    def map_stage(self, chunks: list, query: str) -> list:
        """Xử lý từng chunk"""
        mapped_results = []
        
        for i, chunk in enumerate(chunks):
            print(f"  Processing chunk {i+1}/{len(chunks)}...")
            result = self.model.process_chunk(chunk, query)
            mapped_results.append(result)
        
        return mapped_results
    
    def collapse_stage(self, mapped_results: list, query: str) -> list:
        """Gộp các kết quả lại"""
        # Nếu ít kết quả, không cần collapse
        if len(mapped_results) <= 2:
            return mapped_results
        
        # Group các kết quả
        groups = []
        current_group = []
        current_length = 0
        
        for result in mapped_results:
            text = result.get("text", "")
            token_length = len(self.model.tokenizer.encode(text))
            
            if current_length + token_length > self.collapse_threshold:
                if current_group:
                    groups.append(current_group)
                current_group = [result]
                current_length = token_length
            else:
                current_group.append(result)
                current_length += token_length
        
        if current_group:
            groups.append(current_group)
        
        # Collapse từng group
        collapsed_results = []
        for group in groups:
            combined_text = " ".join([r["text"] for r in group])
            collapse_query = f"{query}\n\nSummarize the following results:\n{combined_text}"
            
            result = self.model.generate(collapse_query)
            collapsed_results.append(result)
        
        return collapsed_results
    
    def reduce_stage(self, collapsed_results: list, query: str) -> Dict:
        """Tổng hợp kết quả cuối cùng"""
        if len(collapsed_results) == 1:
            return collapsed_results[0]
        
        # Kết hợp tất cả kết quả
        combined_text = "\n\n".join([r["text"] for r in collapsed_results])
        
        # Truncate nếu quá dài
        tokens = self.model.tokenizer.encode(combined_text)
        if len(tokens) > self.context_window:
            tokens = tokens[:self.context_window]
            combined_text = self.model.tokenizer.decode(tokens, skip_special_tokens=True)
        
        final_query = f"{query}\n\nBased on these summaries, provide a final comprehensive answer:\n{combined_text}"
        
        final_result = self.model.generate(final_query)
        return final_result
    
    def process_long_text(self, document: str, query: str) -> Dict:
        """
        Xử lý văn bản dài với MapReduce
        
        Args:
            document: Văn bản dài cần xử lý
            query: Câu hỏi/yêu cầu
            
        Returns:
            Dict với keys: "text", "answer", "rationale"
        """
        print(f"📄 Document length: {len(document)} chars, {len(self.model.tokenizer.encode(document))} tokens")
        
        # 1. Chunk văn bản
        chunks = self.chunk_text(document)
        print(f"✂️  Split into {len(chunks)} chunks")
        
        # Nếu chỉ có 1 chunk, xử lý trực tiếp
        if len(chunks) == 1:
            print("📝 Single chunk, processing directly...")
            return self.model.process_chunk(chunks[0], query)
        
        # 2. Map stage
        print("🗺️  Map stage: Processing chunks...")
        mapped_results = self.map_stage(chunks, query)
        
        # 3. Collapse stage (nếu cần)
        if len(mapped_results) > 2:
            print("🔄 Collapse stage: Merging results...")
            collapsed_results = self.collapse_stage(mapped_results, query)
        else:
            collapsed_results = mapped_results
        
        # 4. Reduce stage
        print("📊 Reduce stage: Final aggregation...")
        final_result = self.reduce_stage(collapsed_results, query)
        
        return final_result


# ============= VÍ DỤ SỬ DỤNG =============

if __name__ == "__main__":
    import asyncio
    
    async def test_mapreduce():
        # 1. Khởi tạo model - tokenizer sẽ tự động detect
        ollama_model = LanguageModelOllamaMapReduce(
            model="shmily_006/Qw3:4b_4bit",  # Model finetune của Qwen3
            # tokenizer_name sẽ tự động chọn Qwen/Qwen2.5-7B
            temperature=0.7
        )
        
        # 2. Khởi tạo OllamaMapReduceLLM (custom implementation)
        mapreduce_llm = OllamaMapReduceLLM(
            model=ollama_model,
            context_window=2048,
            collapse_threshold=1024
        )
        
        # 3. Văn bản dài cần xử lý
        document = """
        Hội nghị lần thứ 8 Ban Chấp hành Trung ương Đảng khóa XIII đã diễn ra từ ngày 2-5/10/2023.
        
        Hội nghị đã thảo luận và quyết định nhiều vấn đề quan trọng về phát triển kinh tế - xã hội,
        quốc phòng - an ninh, đối ngoại và xây dựng Đảng. Trung ương đã thông qua Nghị quyết về
        tiếp tục đẩy mạnh công nghiệp hóa, hiện đại hóa đất nước đến năm 2030, tầm nhìn đến năm 2045.
        
        Về phát triển kinh tế, Hội nghị nhấn mạnh cần tập trung phát triển 3 đột phá chiến lược:
        hoàn thiện thể chế kinh tế thị trường định hướng xã hội chủ nghĩa, phát triển nguồn nhân lực,
        và xây dựng hạ tầng đồng bộ, hiện đại. 
        
        Trung ương cũng đã bàn về công tác cán bộ, quyết định điều động, phân công một số cán bộ
        giữ các chức vụ lãnh đạo chủ chốt của Đảng và Nhà nước.
        
        [... Thêm nhiều nội dung chi tiết khác ...]
        """
        
        # 4. Câu hỏi
        query = "Tóm tắt các nội dung chính của Hội nghị lần thứ 8 BCH TW Đảng khóa XIII"
        
        # 5. Xử lý với MapReduce
        print("\n" + "="*70)
        print("Đang xử lý văn bản với MapReduce...")
        print("="*70)
        result = mapreduce_llm.process_long_text(document, query)
        
        print("\n" + "="*70)
        print("KẾT QUẢ:")
        print("="*70)
        print(result["answer"])
        
        # 6. Đóng kết nối
        await ollama_model.aclose()
    
    # Chạy test
    asyncio.run(test_mapreduce())
